{
  "formatVersion": "1.1",
  "component": {
    "group": "com.ilfuta.kmpads",
    "module": "kmp-compose-admob",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-compose-admob-metadata-1.0.4.jar",
          "url": "kmp-compose-admob-1.0.4.jar",
          "size": 3479,
          "sha512": "49bd4be26f1df737b0d50f100cad2ca827657988182e85e21c163ef5ad0a01a22f41293648c8bb16a8b477a0ec501a779d4d1c63bab442fc5b274e222fa991f3",
          "sha256": "c812df2893986873bb8a965cf625346acb58c6dc880614e00c13e5f19a6ca2b8",
          "sha1": "f3cb8f8755fcafbf3d0a39d0188514dbd45a3ecd",
          "md5": "ccbeb7d596aabf182a55a7b24f045d76"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kmp-compose-admob-kotlin-1.0.4-sources.jar",
          "url": "kmp-compose-admob-1.0.4-sources.jar",
          "size": 5130,
          "sha512": "e632fdd8684a5768f1a6cca1ec22a6295a54f91dddad28ab8584c0f40a4f0b3d66afceea86db37d3adaf4d7401b594ec8ae5954713a2a38dc96387c6db155b71",
          "sha256": "98c9f3f4c5d58b318f416d55bcc33da9c30c7a8eadc3ac61cf317c2455605522",
          "sha1": "aca33e51ae038c112f93ffdff7b097ad2a225fd8",
          "md5": "42ce59c92019f893a4ed8679df705632"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmp-compose-admob-android/1.0.4/kmp-compose-admob-android-1.0.4.module",
        "group": "com.ilfuta.kmpads",
        "module": "kmp-compose-admob-android",
        "version": "1.0.4"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmp-compose-admob-android/1.0.4/kmp-compose-admob-android-1.0.4.module",
        "group": "com.ilfuta.kmpads",
        "module": "kmp-compose-admob-android",
        "version": "1.0.4"
      }
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../kmp-compose-admob-android/1.0.4/kmp-compose-admob-android-1.0.4.module",
        "group": "com.ilfuta.kmpads",
        "module": "kmp-compose-admob-android",
        "version": "1.0.4"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmp-compose-admob-iosarm64/1.0.4/kmp-compose-admob-iosarm64-1.0.4.module",
        "group": "com.ilfuta.kmpads",
        "module": "kmp-compose-admob-iosarm64",
        "version": "1.0.4"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmp-compose-admob-iosarm64/1.0.4/kmp-compose-admob-iosarm64-1.0.4.module",
        "group": "com.ilfuta.kmpads",
        "module": "kmp-compose-admob-iosarm64",
        "version": "1.0.4"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmp-compose-admob-iosarm64/1.0.4/kmp-compose-admob-iosarm64-1.0.4.module",
        "group": "com.ilfuta.kmpads",
        "module": "kmp-compose-admob-iosarm64",
        "version": "1.0.4"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmp-compose-admob-iosarm64/1.0.4/kmp-compose-admob-iosarm64-1.0.4.module",
        "group": "com.ilfuta.kmpads",
        "module": "kmp-compose-admob-iosarm64",
        "version": "1.0.4"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmp-compose-admob-iossimulatorarm64/1.0.4/kmp-compose-admob-iossimulatorarm64-1.0.4.module",
        "group": "com.ilfuta.kmpads",
        "module": "kmp-compose-admob-iossimulatorarm64",
        "version": "1.0.4"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmp-compose-admob-iossimulatorarm64/1.0.4/kmp-compose-admob-iossimulatorarm64-1.0.4.module",
        "group": "com.ilfuta.kmpads",
        "module": "kmp-compose-admob-iossimulatorarm64",
        "version": "1.0.4"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmp-compose-admob-iossimulatorarm64/1.0.4/kmp-compose-admob-iossimulatorarm64-1.0.4.module",
        "group": "com.ilfuta.kmpads",
        "module": "kmp-compose-admob-iossimulatorarm64",
        "version": "1.0.4"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kmp-compose-admob-iossimulatorarm64/1.0.4/kmp-compose-admob-iossimulatorarm64-1.0.4.module",
        "group": "com.ilfuta.kmpads",
        "module": "kmp-compose-admob-iossimulatorarm64",
        "version": "1.0.4"
      }
    }
  ]
}
