{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmp-compose-admob/1.0.4/kmp-compose-admob-1.0.4.module",
    "group": "com.ilfuta.kmpads",
    "module": "kmp-compose-admob",
    "version": "1.0.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-compose-admob-release.aar",
          "url": "kmp-compose-admob-android-1.0.4.aar",
          "size": 21235,
          "sha512": "96973a4ae51a97a64dd3a1b7abacb52595302658e191e3116f2aac28f6b13978b102d768597b10c130fd5297cb691ee84074fbadea37f887fff1ef1533121bd6",
          "sha256": "2b9e8589cbe3dbb07eb91ee0d93aad562ee3d0a068e714e69dcee08d49291636",
          "sha1": "781922d401f69dd0a0fbfba06d98c3ddf20c4ccc",
          "md5": "2c5be1cbef3ef52facda05d31fce9f5b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "24.6.0"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-beta03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-beta03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-beta03"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-stdlib-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-common"
            },
            {
              "group": "org.jetbrains.kotlin",
              "module": "kotlin-test-annotations-common"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "kmp-compose-admob-release.aar",
          "url": "kmp-compose-admob-android-1.0.4.aar",
          "size": 21235,
          "sha512": "96973a4ae51a97a64dd3a1b7abacb52595302658e191e3116f2aac28f6b13978b102d768597b10c130fd5297cb691ee84074fbadea37f887fff1ef1533121bd6",
          "sha256": "2b9e8589cbe3dbb07eb91ee0d93aad562ee3d0a068e714e69dcee08d49291636",
          "sha1": "781922d401f69dd0a0fbfba06d98c3ddf20c4ccc",
          "md5": "2c5be1cbef3ef52facda05d31fce9f5b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "kmp-compose-admob-android-1.0.4-sources.jar",
          "url": "kmp-compose-admob-android-1.0.4-sources.jar",
          "size": 5752,
          "sha512": "33fb6bf7c4cb2b8d92f68cf16fad2d22ae63fdbd4f566825191ef93cc54ed0301eb74e01308657a530f704228e363eddd86bc6bfa72c18e7926a33495e7a0feb",
          "sha256": "21de0fc570e91cbe4900ed498a0ee5b677612a373f611f805e639b7aeae0c1fb",
          "sha1": "26ce307d88d20dd1f68bd3f67b8755886a08a407",
          "md5": "31585d6c9ba7327fc826a0995ff3d17b"
        }
      ]
    }
  ]
}
