{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmp-compose-admob/1.0.0/kmp-compose-admob-1.0.0.module",
    "group": "com.ilfuta.kmpads",
    "module": "kmp-compose-admob",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-compose-admob-iosSimulatorArm64Main-1.0.0.klib",
          "url": "kmp-compose-admob-iossimulatorarm64-1.0.0.klib",
          "size": 14097,
          "sha512": "34d503c46f80e04ea752f2c2ef8b202c4a1b7c63faf750acb3e7b8ee8bd4b2cdf6cc3e03607a1c1b4177c67023ec1ec3e61a8b552dc1994bdf84556827b6efb7",
          "sha256": "c33662d758e9076e0535c64747033294eb517d2248d9f3477d5252bac4c93290",
          "sha1": "95886a8cb22ebeaba311d5e4bd323b5247cf82a2",
          "md5": "d712b08616f315d89bc7f35a3714cea7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmp-compose-admob-iossimulatorarm64-1.0.0-sources.jar",
          "url": "kmp-compose-admob-iossimulatorarm64-1.0.0-sources.jar",
          "size": 3903,
          "sha512": "8bdc767fef813aa343874cf2334d00fdd474c4ead32a7f4a05d50f47c0df25d17e6756c6a9ced8b657600d6a74c29ce7176c5b869a1f6fbd343334905aa03c52",
          "sha256": "166cca350354cc26a762808fb1775eb62cf7953c847def595d619120110ba667",
          "sha1": "314743856f8b6b2cae3a071278f8b2acc38d1651",
          "md5": "296ef4377c38a7bbd74e6d7866c00a2a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-compose-admob-1.0.0.kotlin_resources.zip",
          "url": "kmp-compose-admob-iossimulatorarm64-1.0.0-kotlin_resources.kotlin_resources.zip",
          "size": 358,
          "sha512": "c4001b6254a64c174b9d2150e7bf4a1dc8cc181fbede2a2973e68469d80538829b9550cdf95edc84489cf989f73957647d669936843bf5b7dd268559ce25a812",
          "sha256": "4d0296d6dc3fb661fd0aea7e688bccc781caf3e2f95228a74ced1cdca9ca7877",
          "sha1": "eeb6414e9cce27e871ecd043a656204108c98f8e",
          "md5": "2ed499ef4dedb6272d4d19118f0526da"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-compose-admob-iossimulatorarm64-1.0.0-metadata.jar",
          "url": "kmp-compose-admob-iossimulatorarm64-1.0.0-metadata.jar",
          "size": 3626,
          "sha512": "273ab815c5b6fbccbf390271fce768ce3f78d3b102f3243bbff551949ca4d595e6dcce5388a6b7d57a620f8c857e517519550ea1bdab02933fb769581e4fb3ac",
          "sha256": "3a3372e758e8b5c71f0c8dc2fdc65f50065da1458aa9912f42a4be2c94f334cb",
          "sha1": "ab9baaae8460c07ab33ab81104d3c934995f5e14",
          "md5": "e3d77ea11318edfd6f4f549c8ddd573c"
        }
      ]
    }
  ]
}
