{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmp-compose-admob/1.0.0/kmp-compose-admob-1.0.0.module",
    "group": "com.ilfuta.kmpads",
    "module": "kmp-compose-admob",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-compose-admob-iosSimulatorArm64Main-1.0.0.klib",
          "url": "kmp-compose-admob-iossimulatorarm64-1.0.0.klib",
          "size": 14097,
          "sha512": "34d503c46f80e04ea752f2c2ef8b202c4a1b7c63faf750acb3e7b8ee8bd4b2cdf6cc3e03607a1c1b4177c67023ec1ec3e61a8b552dc1994bdf84556827b6efb7",
          "sha256": "c33662d758e9076e0535c64747033294eb517d2248d9f3477d5252bac4c93290",
          "sha1": "95886a8cb22ebeaba311d5e4bd323b5247cf82a2",
          "md5": "d712b08616f315d89bc7f35a3714cea7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmp-compose-admob-iossimulatorarm64-1.0.0-sources.jar",
          "url": "kmp-compose-admob-iossimulatorarm64-1.0.0-sources.jar",
          "size": 3903,
          "sha512": "8bdc767fef813aa343874cf2334d00fdd474c4ead32a7f4a05d50f47c0df25d17e6756c6a9ced8b657600d6a74c29ce7176c5b869a1f6fbd343334905aa03c52",
          "sha256": "166cca350354cc26a762808fb1775eb62cf7953c847def595d619120110ba667",
          "sha1": "314743856f8b6b2cae3a071278f8b2acc38d1651",
          "md5": "296ef4377c38a7bbd74e6d7866c00a2a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-compose-admob-1.0.0.kotlin_resources.zip",
          "url": "kmp-compose-admob-iossimulatorarm64-1.0.0-kotlin_resources.kotlin_resources.zip",
          "size": 358,
          "sha512": "3a1a3810a6907329f96477ec84c90f3aa199a9367832f924d8a668f388608cf6945ff9dbb6d233dc7d6a48dda434f75ee941de82d4328e6d7467da5d54c66097",
          "sha256": "2ccfabc7cd906375d6933c2175705b0a8b3e476889cfc1beddcfaabdd203a4a6",
          "sha1": "a4e67fa24f0d3d3dc425b9426b87ad937d5b9724",
          "md5": "71e8271fda58e431e5b070837b678ec9"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-compose-admob-iossimulatorarm64-1.0.0-metadata.jar",
          "url": "kmp-compose-admob-iossimulatorarm64-1.0.0-metadata.jar",
          "size": 3626,
          "sha512": "5849c111d7983312ece86b3dc929c710113dbb1732e8c192f05b6b2c829cdf271c78fd821255230392f7a4c469a716946c057998d79aa558962b68cde7e890ba",
          "sha256": "62fecc272d54aabba506b2411759bd48e64d37f9518a90045ceed0617ac6a394",
          "sha1": "892f07933f69383f265f9db70b204e33f941a966",
          "md5": "17b28a1a43e5947e854dc7b32e5fd3ea"
        }
      ]
    }
  ]
}
