{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmp-compose-admob/1.0.0/kmp-compose-admob-1.0.0.module",
    "group": "com.ilfuta.kmpads",
    "module": "kmp-compose-admob",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-compose-admob-iosSimulatorArm64Main-1.0.0.klib",
          "url": "kmp-compose-admob-iossimulatorarm64-1.0.0.klib",
          "size": 14097,
          "sha512": "34d503c46f80e04ea752f2c2ef8b202c4a1b7c63faf750acb3e7b8ee8bd4b2cdf6cc3e03607a1c1b4177c67023ec1ec3e61a8b552dc1994bdf84556827b6efb7",
          "sha256": "c33662d758e9076e0535c64747033294eb517d2248d9f3477d5252bac4c93290",
          "sha1": "95886a8cb22ebeaba311d5e4bd323b5247cf82a2",
          "md5": "d712b08616f315d89bc7f35a3714cea7"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmp-compose-admob-iossimulatorarm64-1.0.0-sources.jar",
          "url": "kmp-compose-admob-iossimulatorarm64-1.0.0-sources.jar",
          "size": 3903,
          "sha512": "8bdc767fef813aa343874cf2334d00fdd474c4ead32a7f4a05d50f47c0df25d17e6756c6a9ced8b657600d6a74c29ce7176c5b869a1f6fbd343334905aa03c52",
          "sha256": "166cca350354cc26a762808fb1775eb62cf7953c847def595d619120110ba667",
          "sha1": "314743856f8b6b2cae3a071278f8b2acc38d1651",
          "md5": "296ef4377c38a7bbd74e6d7866c00a2a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-compose-admob-1.0.0.kotlin_resources.zip",
          "url": "kmp-compose-admob-iossimulatorarm64-1.0.0-kotlin_resources.kotlin_resources.zip",
          "size": 358,
          "sha512": "04c0a59fd732911aa5b23b032fdf6ff75a7d3df3f252e3c9f042337cce22ddfd39207c2e304f48babdedbf4c28c7f0f09f27cdfc114c9c345ab2b03e3341eb2e",
          "sha256": "6c4c66d7ed9fd3dd53416e9faa0ded727998c560acc3b6f392b0b35fdf5b7647",
          "sha1": "44f0e8270288565e07d2c1c4104a5d548628fd2c",
          "md5": "a87215ebb7e971d4cbfcf20fa3fa620c"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-compose-admob-iossimulatorarm64-1.0.0-metadata.jar",
          "url": "kmp-compose-admob-iossimulatorarm64-1.0.0-metadata.jar",
          "size": 3626,
          "sha512": "bf26864673e29c40b55b9762bfe36ce9724d533792b9ce7fb0f918d46d37447a74f8f752f5935c1afbb2ceafcb262d6f3a3aea748832dbd164660573d5c03021",
          "sha256": "10ec0ffc3cf1142a6ee412cfeaa77f0314c1b07d25fc3d140bf10e9ef6837af8",
          "sha1": "1fa4a125a7c87ecb608009f485f033573add469e",
          "md5": "863b5b0d10032329a52a9d21fa1fb80b"
        }
      ]
    }
  ]
}
