{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kmp-compose-admob/1.0.0/kmp-compose-admob-1.0.0.module",
    "group": "com.ilfuta.kmpads",
    "module": "kmp-compose-admob",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.3"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-compose-admob-iosArm64Main-1.0.0.klib",
          "url": "kmp-compose-admob-iosarm64-1.0.0.klib",
          "size": 14031,
          "sha512": "aebf347b14c1a01fce88ea6e23747f87b52afbcdd7517aede6d4252046505ad9e3bfc2f58c2d843727dd3cc8e9654daf519e2ba530b49f8bd98c00ea93f109a4",
          "sha256": "3dfa5baef7a5a445952d76931370667fada0ebf72ec26755edacab9b8656a488",
          "sha1": "0790d77a4aa973e7f207320f16d970b91e062e36",
          "md5": "caec765d9ab080669ed9b848078637df"
        }
      ]
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kmp-compose-admob-iosarm64-1.0.0-sources.jar",
          "url": "kmp-compose-admob-iosarm64-1.0.0-sources.jar",
          "size": 3903,
          "sha512": "8bdc767fef813aa343874cf2334d00fdd474c4ead32a7f4a05d50f47c0df25d17e6756c6a9ced8b657600d6a74c29ce7176c5b869a1f6fbd343334905aa03c52",
          "sha256": "166cca350354cc26a762808fb1775eb62cf7953c847def595d619120110ba667",
          "sha1": "314743856f8b6b2cae3a071278f8b2acc38d1651",
          "md5": "296ef4377c38a7bbd74e6d7866c00a2a"
        }
      ]
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-compose-admob-1.0.0.kotlin_resources.zip",
          "url": "kmp-compose-admob-iosarm64-1.0.0-kotlin_resources.kotlin_resources.zip",
          "size": 358,
          "sha512": "33c2988829342863e20544017cc776746d0693cdf0025292a47bc147d34e2184dafc6b8bd0c625d77d1b411e8f89be85c363b49e8f9324f66ff6f551e0b8d943",
          "sha256": "40a9bbc6541005d016e72a7da61b1babb91dd0a42c684adb3c0ededf85048628",
          "sha1": "70633d70b8709babde389ddc3260a8c263623753",
          "md5": "b6a1911bca0b51dbfcbc4ac06694f83d"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "org.jetbrains.compose.runtime",
          "module": "runtime",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.foundation",
          "module": "foundation",
          "version": {
            "requires": "1.9.0-beta03"
          }
        },
        {
          "group": "org.jetbrains.compose.ui",
          "module": "ui",
          "version": {
            "requires": "1.9.0-beta03"
          }
        }
      ],
      "files": [
        {
          "name": "kmp-compose-admob-iosarm64-1.0.0-metadata.jar",
          "url": "kmp-compose-admob-iosarm64-1.0.0-metadata.jar",
          "size": 3626,
          "sha512": "5849c111d7983312ece86b3dc929c710113dbb1732e8c192f05b6b2c829cdf271c78fd821255230392f7a4c469a716946c057998d79aa558962b68cde7e890ba",
          "sha256": "62fecc272d54aabba506b2411759bd48e64d37f9518a90045ceed0617ac6a394",
          "sha1": "892f07933f69383f265f9db70b204e33f941a966",
          "md5": "17b28a1a43e5947e854dc7b32e5fd3ea"
        }
      ]
    }
  ]
}
